CREATE TABLE USER (
    UserID INT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE POST (
    PostID INT PRIMARY KEY,
    AuthorID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    FOREIGN KEY (AuthorID) REFERENCES USER(UserID)
);

CREATE TABLE COMMENT (
    CommentID INT PRIMARY KEY,
    PostID INT NOT NULL,
    UserID INT NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    FOREIGN KEY (PostID) REFERENCES POST(PostID),
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

CREATE TABLE LIKES (
    LikeID INT PRIMARY KEY,
    PostID INT NOT NULL,
    UserID INT NOT NULL,
    LikedAt DATETIME NOT NULL,
    FOREIGN KEY (PostID) REFERENCES POST(PostID),
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);
